name: 'Action Release Milestone'
description: 'Drafts a GitHub release based on a newly closed milestone'
author: 'Ivan Gonzalez Perez'
inputs:
  repo-token:
    description: 'The GITHUB token to authenticate to the repository'
    required: true
outputs:
  release-url: 
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-token }}