name: 'Action Release Milestone'
description: 'Drafts a GitHub release based on a newly closed milestone'
author: 'Ivan Gonzalez Perez'
outputs:
  release-url: 
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'docker'
  image: 'Dockerfile'